edition = "2024"
unstable_features = true

format_code_in_doc_comments = true
format_strings = true

imports_layout = "Vertical"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

reorder_impl_items = true
use_try_shorthand = true
wrap_comments = true
overflow_delimited_expr = true
use_field_init_shorthand = true

condense_wildcard_suffixes = true
